name: go_ticket
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  intl: ^0.20.3
  shared_preferences: ^2.5.5
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/logo.png
    - assets/logo_hotel.png
    - assets/Logo Go Ticket Hotel.png
